//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urban.AI.Infrastructure.Auth.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeycloakResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeycloakResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urban.AI.Infrastructure.Auth.Resources.KeycloakResources", typeof(KeycloakResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to acquire access token do to authentication failure.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        internal static string FailedToRetrieveUsers {
            get {
                return ResourceManager.GetString("FailedToRetrieveUsers", resourceCulture);
            }
        }
        
        internal static string FailedToRetrieveUser {
            get {
                return ResourceManager.GetString("FailedToRetrieveUser", resourceCulture);
            }
        }
        
        internal static string UserNotFoundInKeycloak {
            get {
                return ResourceManager.GetString("UserNotFoundInKeycloak", resourceCulture);
            }
        }
        
        internal static string FailedToUpdateUser {
            get {
                return ResourceManager.GetString("FailedToUpdateUser", resourceCulture);
            }
        }
        
        internal static string FailedToDeleteUser {
            get {
                return ResourceManager.GetString("FailedToDeleteUser", resourceCulture);
            }
        }
        
        internal static string FailedToAssignRoles {
            get {
                return ResourceManager.GetString("FailedToAssignRoles", resourceCulture);
            }
        }
        
        internal static string FailedToRetrieveUserRoles {
            get {
                return ResourceManager.GetString("FailedToRetrieveUserRoles", resourceCulture);
            }
        }
        
        internal static string FailedToRetrieveRoles {
            get {
                return ResourceManager.GetString("FailedToRetrieveRoles", resourceCulture);
            }
        }
        
        internal static string FailedToRetrieveRole {
            get {
                return ResourceManager.GetString("FailedToRetrieveRole", resourceCulture);
            }
        }
        
        internal static string FailedToCreateRole {
            get {
                return ResourceManager.GetString("FailedToCreateRole", resourceCulture);
            }
        }
        
        internal static string FailedToUpdateRole {
            get {
                return ResourceManager.GetString("FailedToUpdateRole", resourceCulture);
            }
        }
        
        internal static string FailedToDeleteRole {
            get {
                return ResourceManager.GetString("FailedToDeleteRole", resourceCulture);
            }
        }
        
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
    }
}
