// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Urban.AI.Infrastructure.Database;

#nullable disable

namespace Urban.AI.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207141936_UpdateRadicateNumberToStandardFormat")]
    partial class UpdateRadicateNumberToStandardFormat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Geography.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentDaneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("department_dane_code");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasAlternateKey("DepartmentDaneCode")
                        .HasName("ak_departments_department_dane_code");

                    b.HasIndex("DepartmentDaneCode")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_department_dane_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_departments_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Geography.Municipality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentDaneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("department_dane_code");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("MunicipalityDaneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("municipality_dane_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_municipalities");

                    b.HasAlternateKey("MunicipalityDaneCode")
                        .HasName("ak_municipalities_municipality_dane_code");

                    b.HasIndex("DepartmentDaneCode")
                        .HasDatabaseName("ix_municipalities_department_dane_code");

                    b.HasIndex("MunicipalityDaneCode")
                        .IsUnique()
                        .HasDatabaseName("ix_municipalities_municipality_dane_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_municipalities_name");

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Geography.Township", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MunicipalityDaneCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("municipality_dane_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TownshipDaneCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("township_dane_code");

                    b.HasKey("Id")
                        .HasName("pk_townships");

                    b.HasIndex("MunicipalityDaneCode")
                        .HasDatabaseName("ix_townships_municipality_dane_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_townships_name");

                    b.HasIndex("TownshipDaneCode")
                        .IsUnique()
                        .HasDatabaseName("ix_townships_township_dane_code");

                    b.ToTable("townships", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Incidents.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Incidents.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalComment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("additional_comment");

                    b.Property<string>("AiDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ai_description");

                    b.Property<DateTime?>("AttentionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attention_date");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CitizenEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("citizen_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<Guid?>("LeaderId")
                        .HasColumnType("uuid")
                        .HasColumnName("leader_id");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<string>("RadicateNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("radicate_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategory_id");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_incidents_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_incidents_created_at");

                    b.HasIndex("LeaderId")
                        .HasDatabaseName("ix_incidents_leader_id");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_incidents_municipality_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_incidents_priority");

                    b.HasIndex("RadicateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_incidents_radicate_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_incidents_status");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_incidents_subcategory_id");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Incidents.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subcategories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_subcategories_category_id");

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_subcategories_category_id_name");

                    b.ToTable("subcategories", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Leaders.Leader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("longitude");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("municipality_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_leaders");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_leaders_department_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_leaders_is_active");

                    b.HasIndex("MunicipalityId")
                        .HasDatabaseName("ix_leaders_municipality_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_leaders_user_id");

                    b.ToTable("leaders", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_organizations_is_active");

                    b.HasIndex("OrganizationName")
                        .HasDatabaseName("ix_organizations_organization_name");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_user_id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Urban.AI.Domain.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "users:read"
                        });
                });

            modelBuilder.Entity("Urban.AI.Domain.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Registered"
                        });
                });

            modelBuilder.Entity("Urban.AI.Domain.Users.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("Urban.AI.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Urban.AI.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_role_roles_id");

                    b.HasOne("Urban.AI.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_user_users_id");
                });

            modelBuilder.Entity("Urban.AI.Domain.Geography.Municipality", b =>
                {
                    b.HasOne("Urban.AI.Domain.Geography.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentDaneCode")
                        .HasPrincipalKey("DepartmentDaneCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_municipalities_departments_department_dane_code");
                });

            modelBuilder.Entity("Urban.AI.Domain.Geography.Township", b =>
                {
                    b.HasOne("Urban.AI.Domain.Geography.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalityDaneCode")
                        .HasPrincipalKey("MunicipalityDaneCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_townships_municipalities_municipality_dane_code");
                });

            modelBuilder.Entity("Urban.AI.Domain.Incidents.Incident", b =>
                {
                    b.HasOne("Urban.AI.Domain.Incidents.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incidents_categories_category_id");

                    b.HasOne("Urban.AI.Domain.Leaders.Leader", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incidents_leader_leader_id");

                    b.HasOne("Urban.AI.Domain.Geography.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_municipalities_municipality_id");

                    b.HasOne("Urban.AI.Domain.Incidents.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incidents_subcategory_subcategory_id");

                    b.OwnsOne("Urban.AI.Domain.Incidents.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("location_latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("location_longitude");

                            b1.HasKey("IncidentId");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("IncidentId")
                                .HasConstraintName("fk_incidents_incidents_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Leader");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Municipality");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("Urban.AI.Domain.Incidents.Subcategory", b =>
                {
                    b.HasOne("Urban.AI.Domain.Incidents.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subcategories_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Urban.AI.Domain.Leaders.Leader", b =>
                {
                    b.HasOne("Urban.AI.Domain.Geography.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaders_departments_department_id");

                    b.HasOne("Urban.AI.Domain.Geography.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaders_municipalities_municipality_id");

                    b.HasOne("Urban.AI.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaders_user_user_id");

                    b.Navigation("Department");

                    b.Navigation("Municipality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Urban.AI.Domain.Organizations.Organization", b =>
                {
                    b.HasOne("Urban.AI.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organizations_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Urban.AI.Domain.Users.RolePermission", b =>
                {
                    b.HasOne("Urban.AI.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Urban.AI.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("Urban.AI.Domain.Users.User", b =>
                {
                    b.OwnsOne("Urban.AI.Domain.Users.UserDetails", "UserDetails", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("UserId")
                                .HasName("pk_user_details");

                            b1.ToTable("user_details", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_details_users_id");

                            b1.OwnsOne("Urban.AI.Domain.Users.ValueObjects.ContactInfo", "ContactInfo", b2 =>
                                {
                                    b2.Property<Guid>("UserDetailsUserId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Biography")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("contact_info_biography");

                                    b2.Property<string>("PhoneNumber")
                                        .IsRequired()
                                        .HasMaxLength(15)
                                        .HasColumnType("character varying(15)")
                                        .HasColumnName("contact_info_phone_number");

                                    b2.Property<string>("PictureUrl")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("contact_info_picture_url");

                                    b2.HasKey("UserDetailsUserId");

                                    b2.ToTable("user_details");

                                    b2.WithOwner()
                                        .HasForeignKey("UserDetailsUserId")
                                        .HasConstraintName("fk_user_details_user_details_id");
                                });

                            b1.OwnsOne("Urban.AI.Domain.Users.ValueObjects.PersonalInfo", "PersonalInfo", b2 =>
                                {
                                    b2.Property<Guid>("UserDetailsUserId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateOnly>("BirthDate")
                                        .HasColumnType("date")
                                        .HasColumnName("personal_info_birth_date");

                                    b2.Property<string>("DocumentNumber")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("personal_info_document_number");

                                    b2.Property<string>("DocumentType")
                                        .IsRequired()
                                        .HasMaxLength(40)
                                        .HasColumnType("character varying(40)")
                                        .HasColumnName("personal_info_document_type");

                                    b2.Property<string>("Gender")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("personal_info_gender");

                                    b2.HasKey("UserDetailsUserId");

                                    b2.ToTable("user_details");

                                    b2.WithOwner()
                                        .HasForeignKey("UserDetailsUserId")
                                        .HasConstraintName("fk_user_details_user_details_id");
                                });

                            b1.Navigation("ContactInfo")
                                .IsRequired();

                            b1.Navigation("PersonalInfo")
                                .IsRequired();
                        });

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("Urban.AI.Domain.Incidents.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
