//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urban.AI.Domain.Incidents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IncidentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public IncidentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Urban.AI.Domain.Incidents.Resources.IncidentResources", typeof(IncidentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incident was not found.
        /// </summary>
        public static string IncidentNotFound {
            get {
                return ResourceManager.GetString("IncidentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incident image is required.
        /// </summary>
        public static string IncidentImageRequired {
            get {
                return ResourceManager.GetString("IncidentImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incident location is required.
        /// </summary>
        public static string IncidentLocationRequired {
            get {
                return ResourceManager.GetString("IncidentLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incident image format is invalid. Only JPEG and PNG formats are allowed.
        /// </summary>
        public static string IncidentInvalidImageFormat {
            get {
                return ResourceManager.GetString("IncidentInvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incident image is too large. Maximum size allowed is {0} MB.
        /// </summary>
        public static string IncidentImageTooLarge {
            get {
                return ResourceManager.GetString("IncidentImageTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to analyze the incident image.
        /// </summary>
        public static string IncidentAnalysisFailed {
            get {
                return ResourceManager.GetString("IncidentAnalysisFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No leader available for the incident location.
        /// </summary>
        public static string IncidentNoLeaderAvailable {
            get {
                return ResourceManager.GetString("IncidentNoLeaderAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        public static string IncidentInvalidEmail {
            get {
                return ResourceManager.GetString("IncidentInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The municipality was not found for the provided location.
        /// </summary>
        public static string IncidentMunicipalityNotFound {
            get {
                return ResourceManager.GetString("IncidentMunicipalityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image stream is required.
        /// </summary>
        public static string IncidentImageStreamRequired {
            get {
                return ResourceManager.GetString("IncidentImageStreamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image filename is required.
        /// </summary>
        public static string IncidentImageFilenameRequired {
            get {
                return ResourceManager.GetString("IncidentImageFilenameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be between -90 and 90.
        /// </summary>
        public static string IncidentInvalidLatitude {
            get {
                return ResourceManager.GetString("IncidentInvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be between -180 and 180.
        /// </summary>
        public static string IncidentInvalidLongitude {
            get {
                return ResourceManager.GetString("IncidentInvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comment must not exceed 500 characters.
        /// </summary>
        public static string IncidentCommentTooLong {
            get {
                return ResourceManager.GetString("IncidentCommentTooLong", resourceCulture);
            }
        }
    }
}
